- name: tileserver compose restart
  listen: "tileserver restart"
  community.docker.docker_compose_v2:
    project_src: '{{ tileserver_path }}'
    state: present
    restarted: True

- name: tileserver clear nginx cache # noqa no-changed-when
  listen:
    - "tileserver restart"
  command:
    cmd: 'rm {{ tileserver_path }}/nginx/cache/* -rf'
  when: tileserver_clear_cache | bool
