---
webserver_redirect_path: '/container/webserver_redirect'

webserver_redirect_domain: 'redirect.{{ ansible_fqdn }}'
webserver_redirect_addon_domains: []
webserver_redirect_domains: '{{ [webserver_redirect_domain] + webserver_redirect_addon_domains }}'

webserver_redirect_destination: 'https://{{ ansible_domain }}'
webserver_redirect_code: '301' # 301: permanent, 302: temporary

webserver_redirect_nginx_image: nginxinc/nginx-unprivileged:stable-alpine

# location specific redirects
webserver_redirect_locations: []

# webserver_redirect_locations:
#   - location: '~ /bar'
#     target: https://example.com/bar.html
#     code: 301
#   - location: /foo
#     target: https://example.com/foo.html
#     code: 301

# pull docker images (docker compose pull)
webserver_redirect_docker_pull: '{{ global_docker_pull | default(False) }}'
