# zfs ansible defaults

zfs_managed_pools:
  - zfsdata
  - zfsbulk

zfs_zpool_properties:
  atime: on
  relatime: on
  xattr: sa
  acltype: posix
  # snapdir: visible

zfs_zpool_autotrim: on

zfs_datasets: []

zfs_extra_zfs_properties_default:
  relatime: on

# ZFS Permission delegation
# zfs_delegate:
#   'zfsdata/container/backuppc/data':
#     descendents: no
#     everyone: no
#     local: no
#     permissions:
#       - send
#       - hold
#       - snapshot
#       - destroy
#     recursive: no
#     state: present
#     users:
#       - officebackup

zfs_metrics_textfile_dir: '{{ node_exporter_textfile_dir | default("/var/lib/node_exporter") }}'

zfs_dataset_property_metrics: False
zfs_dataset_property_metrics_include_datasets: []
zfs_dataset_property_metrics_exclude_datasets: []

# # Example with multiple includes and exclude:
# zfs_dataset_property_metrics: True
# zfs_dataset_property_metrics_include_datasets:
#   - zfsdata
#   - zfsdata/sync
#   - zfsdata/sync/backup3.*
#   - zfsdata/sync/backup4
# zfs_dataset_property_metrics_exclude_datasets: # []
#   - .*/archive
