# handlers file for VictoriaMetrics
---

- name: "vmagent-daemon-reload"
  become: true
  systemd:
    daemon_reload: true

- name: vmagent-restart
  become: true
  service:
    name: vic-vmagent
    state: restarted

- name: vmagent-reload
  service:
    name: vic-vmagent
    state: reloaded
