---
# defaults file for promtail deployment
promtail_local_cache_dir: '{{ local_cache_dir | default("/tmp") }}'
promtail_path: '/container/promtail'

promtail_docker_pull: '{{ global_docker_pull | default(False) }}'
promtail_loki_server: 'loki.{{ ansible_domain }}'
promtail_loki_url: https://{{ promtail_loki_server }}/loki/api/v1/push
promtail_loki_username: testuser
promtail_loki_password: password

promtail_scrape_configs_default:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          category: 'serverlogs'
          job: varlogs
          __path__: /var/log/*log

  - job_name: apt
    static_configs:
      - targets:
          - localhost
        labels:
          category: 'serverlogs'
          job: varlogs
          __path__: /var/log/apt/*log
    pipeline_stages: []

  - job_name: journal
    journal:
      path: /var/log/journal/
      labels:
        category: 'serverlogs'
        job: journallogs
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        # remove .service
        # regex: '(.+)\.service'
        # replacement: '$1'
        target_label: 'systemd_unit'

# additional scrape_configs
promtail_scrape_configs: [{}]

# Example
# promtail_scrape_configs:
#   - job_name: gitlab
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           category: 'serverlogs'
#           job: varlogs
#           __path__: /var/log/gitlab/*/*.log

# deploy mode (binary/docker)
# docker: use docker compose in /container/promtail
# binary: download binary, install systemd service
promtail_deploy_mode: binary

promtail_config_dir: "{{ '/container/promtail' if promtail_deploy_mode == 'docker' else '/etc/promtail' }}"
promtail_positions_path: "{{ '/data/promtail' if promtail_deploy_mode == 'docker' else '/var/log/promtail' }}"

promtail_version: 2.9.2 # also update checkum
# checksum of promtail-linux-amd64.zip from https://github.com/grafana/loki/releases
# wget -q -O - https://github.com/grafana/loki/releases/download/v2.9.2/SHA256SUMS | grep promtail-linux-amd64.zip
promtail_checksum: f2d4f59e4dee505eee9c2c28e2eebb89442e7b544144aff2b7d03a57cafbaf58

promtail_server_disable: True
promtail_server_http_listen_address: 0.0.0.0

# additional groups for user promtail to read files
promtail_additional_groups:
  - adm
  - systemd-journal

# run promtail with user. Allows overriding to root (for debugging)
promtail_user: promtail
