version: "3.7"

services:

  promtail:
    image: grafana/promtail:{{ promtail_version }}
    restart: always
    volumes:
      - /var/log:/var/log:ro
      - ./data/promtail:/data/promtail
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    expose:
      - 9080
    networks:
      - loki
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'

networks:
  loki:
  webproxy:
    external: True
    name: webproxy
