# Loki handlers

- name: loki-restart-loki
  community.docker.docker_compose_v2:
    project_src: '{{ loki_path }}'
    state: restarted
    services:
      - loki

- name: loki-restart-gateway
  community.docker.docker_compose_v2:
    project_src: '{{ loki_path }}'
    state: restarted
    services:
      - nginx-gateway

- name: loki-vmagent-restart
  become: true
  service:
    name: vic-vmagent
    state: restarted
